"""Suit-agnosticism guarantees for the observation encoding and network.

The bidding policy head previously carried an arbitrary, hand-independent
per-suit anchor (it would "Call Clubs" holding zero clubs) because suits were
encoded and output in fixed absolute slots with no shared parameters, and the
round-2 call logits saw far too little gradient to converge. The encoding
(euchre/infoset.py) and PolicyValueNet (rebel/networks.py) were rebuilt to be
suit-agnostic by construction: everything is encoded relative to a reference
suit, and shared per-suit / per-card towers process each suit identically, so
the two off-color ("green") suits are guaranteed the same weights.

These tests pin that guarantee: the observation and the network must be
exactly equivariant under every color-preserving suit relabeling (the 8-element
group generated by swapping within each color and swapping the colors), which
includes the green-green swap. Equivariance is exact for the encoding and to
float precision for the net.
"""

import copy
import random

import numpy as np
import torch

from euchre.cards import Card, Suit
from euchre.game import EuchreState
from euchre.actions import (
    Play, Discard, Call, action_to_index, index_to_action, NUM_ACTIONS,
)
from euchre.infoset import (
    observation_tensor, SUIT_OFF, SUIT_BLOCK_DIM, CARD_OFF, CARD_FEAT_DIM,
    NUM_SUITS,
)
from euchre.cards import NUM_CARDS
from rebel.networks import PolicyValueNet


# --- the color-preserving suit-relabeling group -----------------------------

def _compose(a, b):
    return {s: a[b[s]] for s in Suit}


def color_preserving_group():
    """All 8 suit permutations preserving the color partition {{C,S},{H,D}},
    built by closure from three generators (swap blacks, swap reds, swap
    colors)."""
    gB = {Suit.CLUBS: Suit.SPADES, Suit.SPADES: Suit.CLUBS,
          Suit.DIAMONDS: Suit.DIAMONDS, Suit.HEARTS: Suit.HEARTS}
    gR = {Suit.CLUBS: Suit.CLUBS, Suit.SPADES: Suit.SPADES,
          Suit.DIAMONDS: Suit.HEARTS, Suit.HEARTS: Suit.DIAMONDS}
    gC = {Suit.CLUBS: Suit.DIAMONDS, Suit.SPADES: Suit.HEARTS,
          Suit.DIAMONDS: Suit.CLUBS, Suit.HEARTS: Suit.SPADES}
    ident = {s: s for s in Suit}
    group = {tuple(ident[s] for s in Suit): ident}
    frontier = [ident]
    while frontier:
        x = frontier.pop()
        for g in (gB, gR, gC):
            y = _compose(g, x)
            k = tuple(y[s] for s in Suit)
            if k not in group:
                group[k] = y
                frontier.append(y)
    return list(group.values())


def _relabel_card(c, pi):
    return Card(pi[c.suit], c.rank)


def _relabel_state(state, pi):
    s = copy.deepcopy(state)
    s.hands = [[_relabel_card(c, pi) for c in h] for h in s.hands]
    if s.up_card is not None:
        s.up_card = _relabel_card(s.up_card, pi)
    if s.trump is not None:
        s.trump = pi[s.trump]
    if s.turned_down is not None:
        s.turned_down = pi[s.turned_down]
    s.completed_tricks = [(w, [(pl, _relabel_card(c, pi)) for pl, c in plays])
                          for w, plays in s.completed_tricks]
    s.current_trick = [(pl, _relabel_card(c, pi)) for pl, c in s.current_trick]
    return s


def _permute_obs(obs, pi):
    """Apply pi to an observation: move suit-blocks and card-blocks to the
    slots of their relabeled suits/cards."""
    out = obs.copy()
    for s in Suit:
        src = SUIT_OFF + int(s) * SUIT_BLOCK_DIM
        dst = SUIT_OFF + int(pi[s]) * SUIT_BLOCK_DIM
        out[dst:dst + SUIT_BLOCK_DIM] = obs[src:src + SUIT_BLOCK_DIM]
    for cid in range(NUM_CARDS):
        ncid = _relabel_card(Card.from_id(cid), pi).id
        src = CARD_OFF + cid * CARD_FEAT_DIM
        dst = CARD_OFF + ncid * CARD_FEAT_DIM
        out[dst:dst + CARD_FEAT_DIM] = obs[src:src + CARD_FEAT_DIM]
    return out


def _perm_action(a, pi):
    if isinstance(a, Play):
        return Play(_relabel_card(a.card, pi))
    if isinstance(a, Discard):
        return Discard(_relabel_card(a.card, pi))
    if isinstance(a, Call):
        return Call(pi[a.suit], a.alone)
    return a  # OrderUp / Pass reference the (permuted) up-card suit itself


def _permute_logits(logits, pi):
    out = np.empty_like(logits)
    for i in range(NUM_ACTIONS):
        out[action_to_index(_perm_action(index_to_action(i), pi))] = logits[i]
    return out


def _sample_states(n, seed):
    """A mix of bidding, discard, and play states (non-terminal)."""
    rng = random.Random(seed)
    out = []
    while len(out) < n:
        s = EuchreState.new_hand(dealer=rng.randint(0, 3)).deal(rng)
        for _ in range(rng.randint(0, 14)):
            if s.is_terminal():
                break
            s = s.apply(rng.choice(s.legal_actions()))
        if not s.is_terminal():
            out.append(s)
    return out


def test_group_is_size_eight():
    assert len(color_preserving_group()) == 8


def test_observation_equivariant_under_relabeling():
    perms = color_preserving_group()
    for st in _sample_states(40, 1):
        p = st.current_player
        base = observation_tensor(st, p)
        for pi in perms:
            got = observation_tensor(_relabel_state(st, pi), p)
            want = _permute_obs(base, pi)
            assert np.array_equal(got, want)  # exact -- pure relabeling


def test_network_equivariant_under_relabeling():
    torch.manual_seed(0)
    net = PolicyValueNet()
    net.eval()
    perms = color_preserving_group()
    for st in _sample_states(25, 2):
        p = st.current_player
        obs = torch.from_numpy(observation_tensor(st, p)).unsqueeze(0)
        with torch.no_grad():
            lg, val = net(obs)
        lg = lg.squeeze(0).numpy()
        val = float(val)
        for pi in perms:
            robs = torch.from_numpy(
                observation_tensor(_relabel_state(st, pi), p)).unsqueeze(0)
            with torch.no_grad():
                rlg, rval = net(robs)
            rlg = rlg.squeeze(0).numpy()
            assert np.allclose(rlg, _permute_logits(lg, pi), atol=1e-5)
            assert abs(float(rval) - val) < 1e-5


def test_greens_have_no_hand_independent_anchor():
    """With any hand, the two green suits' Call logits are interchangeable:
    swapping the greens swaps exactly those two logits and nothing else. This
    is the specific guarantee that killed the drifting Clubs/Hearts anchor."""
    torch.manual_seed(0)
    net = PolicyValueNet()
    net.eval()
    # Green swap relative to a red reference (Hearts) is the black-black swap.
    swap_blacks = {Suit.CLUBS: Suit.SPADES, Suit.SPADES: Suit.CLUBS,
                   Suit.DIAMONDS: Suit.DIAMONDS, Suit.HEARTS: Suit.HEARTS}
    for st in _sample_states(20, 3):
        p = st.current_player
        obs = torch.from_numpy(observation_tensor(st, p)).unsqueeze(0)
        robs = torch.from_numpy(
            observation_tensor(_relabel_state(st, swap_blacks), p)).unsqueeze(0)
        with torch.no_grad():
            lg = net(obs)[0].squeeze(0).numpy()
            rlg = net(robs)[0].squeeze(0).numpy()
        c = action_to_index(Call(Suit.CLUBS))
        s = action_to_index(Call(Suit.SPADES))
        # swapping the two greens swaps their call logits
        assert abs(rlg[c] - lg[s]) < 1e-5
        assert abs(rlg[s] - lg[c]) < 1e-5
